---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-leader
  template:
    metadata:
      labels:
        name: redis-leader
    spec:
      containers:
      - image: "docker.io/redis:6.0.5"
        name: redis-leader
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: dev
spec:
  selector:
    name: redis-leader
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
