---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-follower
  template:
    metadata:
      labels:
        name: redis-follower
    spec:
      containers:
      - image: "gcr.io/google_samples/gb-redis-follower:v2"
        name: redis-follower
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: dev
spec:
  selector:
    name: redis-follower
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
